# Generated by Django 4.0.5 on 2022-08-04 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0002_alter_task_datetime_note_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryStatusTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_history', models.DateTimeField()),
                ('status_history', models.CharField(max_length=150)),
                ('employee_history', models.CharField(max_length=150)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.task')),
            ],
            options={
                'verbose_name': 'История изменения статуса задачи',
                'verbose_name_plural': 'История изменения статуса задач',
            },
        ),
        migrations.CreateModel(
            name='HistoryNoteTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_history', models.DateTimeField()),
                ('note_history', models.CharField(max_length=150)),
                ('employee_history', models.CharField(max_length=150)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.task')),
            ],
            options={
                'verbose_name': 'История изменения примечания задачи',
                'verbose_name_plural': 'История изменения примечаний задач',
            },
        ),
    ]
