# Generated by Django 4.0.5 on 2022-08-10 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historynotetask',
            options={'verbose_name': 'примечание задачи', 'verbose_name_plural': 'примечание задач'},
        ),
        migrations.AlterModelOptions(
            name='historystatustask',
            options={'verbose_name': 'статус задачи', 'verbose_name_plural': 'статус задач'},
        ),
    ]
