# Generated by Django 4.0.5 on 2022-08-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CounterpartyTO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=150)),
                ('contract', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'контрагент: техническое обслуживание',
                'verbose_name_plural': 'контрагенты: техническое обслуживание',
            },
        ),
        migrations.CreateModel(
            name='CounterpartyWarrantyObligations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=150)),
                ('contract', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'контрагент: гарантийные обязательства',
                'verbose_name_plural': 'контрагенты: гарантийные обязательства',
            },
        ),
    ]
