# Generated by Django 4.0.5 on 2022-08-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CounterpartyTO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=150)),
                ('contract', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Контрагент: техническое обслуживание',
                'verbose_name_plural': 'Контрагенты: техническое обслуживание',
            },
        ),
        migrations.CreateModel(
            name='CountrpartyWarrantyObligations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=150)),
                ('contract', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Контрагент: гарантийные обязательства',
                'verbose_name_plural': 'Контрагенты: гарантийные обязательства',
            },
        ),
    ]
