# Generated by Django 4.0.5 on 2022-08-02 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counterparty', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CountrpartyWarrantyObligations',
            new_name='CounterpartyWarrantyObligations',
        ),
    ]
