# Generated by Django 4.0.5 on 2022-08-15 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counterparty', '0003_counterparty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counterparty',
            options={'verbose_name': 'контрагент', 'verbose_name_plural': 'контрагент'},
        ),
    ]
