# Generated by Django 4.0.5 on 2022-08-16 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counterparty', '0004_alter_counterparty_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CounterpartyTO',
        ),
        migrations.DeleteModel(
            name='CounterpartyWarrantyObligations',
        ),
        migrations.AlterModelOptions(
            name='counterparty',
            options={'verbose_name': 'контрагента', 'verbose_name_plural': 'контрагент'},
        ),
    ]
