# Generated by Django 4.0.5 on 2022-08-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_task', models.DateField()),
                ('time_task', models.TimeField()),
                ('text_task', models.TextField()),
                ('address_task', models.CharField(default='Офис Эртел', max_length=500)),
                ('author_task', models.CharField(max_length=120)),
                ('employee_task', models.CharField(max_length=120)),
                ('line_task', models.DateField(max_length=150)),
                ('status_task', models.CharField(default='Отдано в разработку', max_length=150)),
                ('business_trip', models.CharField(default='Не командировка', max_length=150)),
                ('type_task', models.CharField(default='Офис', max_length=150)),
                ('note_task', models.CharField(default='', max_length=250)),
                ('datetime_note_task', models.DateTimeField(default='2022-08-04 11:18:56.239443')),
            ],
            options={
                'verbose_name': 'задача',
                'verbose_name_plural': 'задачи',
            },
        ),
    ]
