# Generated by Django 4.0.5 on 2022-08-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='datetime_note_task',
            field=models.CharField(default='', max_length=150),
        ),
    ]
