# Generated by Django 4.0.5 on 2022-06-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='chat_id',
            field=models.CharField(default=815286607, max_length=150),
            preserve_default=False,
        ),
    ]
