# Generated by Django 4.0.5 on 2022-07-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_profile_options_alter_task_options_worktask'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worktask',
            options={'verbose_name': 'Учёт рабочего времени', 'verbose_name_plural': 'Учёт рабочего времени'},
        ),
        migrations.AlterField(
            model_name='worktask',
            name='date_work_task',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='worktask',
            name='time_work_task',
            field=models.CharField(max_length=150),
        ),
    ]
