# Generated by Django 4.0.5 on 2022-08-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_task_datetime_note_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='datetime_note_task',
            field=models.DateField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='task',
            name='note_task',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
