# Generated by Django 4.0.5 on 2022-07-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_alter_worktask_date_work_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktask',
            name='status_work_task',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
