# Generated by Django 4.0.5 on 2022-07-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_worktask_status_work_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
            },
        ),
    ]
