# Generated by Django 4.0.5 on 2022-07-05 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='position_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='task.position'),
            preserve_default=False,
        ),
    ]
