# Generated by Django 4.0.5 on 2022-07-05 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_profile_position_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='position_id',
            new_name='position_dep_id',
        ),
    ]
