# Generated by Django 4.0.5 on 2022-08-05 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_remove_task_datetime_note_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='datetime_note_task',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 8, 5, 15, 4, 30, 588557), max_length=150),
        ),
    ]
