# Generated by Django 4.0.5 on 2022-07-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_alter_profile_position_dep_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='line_task',
            field=models.DateField(max_length=150),
        ),
    ]
