# Generated by Django 4.0.5 on 2022-07-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_alter_task_line_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status_task',
            field=models.CharField(default='Отдано в разработку', max_length=150),
        ),
    ]
