# Generated by Django 4.0.5 on 2022-08-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0014_alter_task_datetime_note_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='datetime_note_task',
            field=models.DateTimeField(blank=True, max_length=150, null=True),
        ),
    ]
