# Generated by Django 4.0.5 on 2022-07-26 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0014_counterparty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counterparty',
            name='type',
        ),
    ]
