# Generated by Django 4.0.5 on 2022-08-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0015_alter_task_datetime_note_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'задачу', 'verbose_name_plural': 'задачи'},
        ),
        migrations.AddField(
            model_name='task',
            name='address_obj_task',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='task',
            name='urgency_task',
            field=models.CharField(default='', max_length=150),
        ),
    ]
