# Generated by Django 4.0.5 on 2022-07-26 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0017_alter_task_address_task'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Counterparty',
            new_name='CounterpartyTO',
        ),
    ]
