# Generated by Django 4.0.5 on 2022-07-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0018_rename_counterparty_counterpartyto'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountrpartyWarrantyObligations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=150)),
                ('contract', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Контрагент: гарантийные обязательства',
                'verbose_name_plural': 'Контрагенты: гарантийные обязательства',
            },
        ),
        migrations.AlterModelOptions(
            name='counterpartyto',
            options={'verbose_name': 'Контрагент: ТО', 'verbose_name_plural': 'Контрагенты: ТО'},
        ),
    ]
