# Generated by Django 4.0.5 on 2022-10-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0019_alter_bestemployee_time_do_object_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestemployee',
            name='date_be',
            field=models.DateField(blank=True),
        ),
    ]
