# Generated by Django 4.0.5 on 2022-10-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0020_alter_bestemployee_date_be'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestemployee',
            name='date_be',
            field=models.DateField(blank=True, null=True),
        ),
    ]
