# Generated by Django 4.0.5 on 2022-07-29 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0021_task_business_trip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkTask',
        ),
    ]
