# Generated by Django 4.0.5 on 2022-07-29 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0022_delete_worktask'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CounterpartyTO',
        ),
        migrations.DeleteModel(
            name='CountrpartyWarrantyObligations',
        ),
    ]
