# Generated by Django 4.0.5 on 2022-07-29 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0024_remove_position_department_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='business_trip',
        ),
    ]
