# Generated by Django 4.0.5 on 2022-07-29 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0025_remove_task_business_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='business_trip',
            field=models.CharField(default='Не командировка', max_length=150),
        ),
    ]
