# Generated by Django 4.0.5 on 2022-07-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0026_task_business_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='type_task',
            field=models.CharField(default='Офис', max_length=150),
        ),
    ]
